### ISSUE TITLE
Quizid as a parameter

### ISSUE THREAD

**Issue by jharej** [vadimonus/moodle-local_deleteoldquizattempts#1]
Hi,

could you upgrade this plugin to have a possibility to give quizid as a parameter? We have just few quizzes where we would like to delete quiz attempts. 

thanks and bye

**Comment by alexippo** [comment]
Hi, i have error while cli command, how can I fix it
Default exception handler: Не знайдено запис в таблиці бази даних context. Debug: SELECT * FROM {context} WHERE id = ?
[array (
0 => '153809',
)]
Error code: invalidrecord
* line 1562 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 5213 of /lib/accesslib.php: call to moodle_database->get_record()
* line 5602 of /lib/accesslib.php: call to context::instance_by_id()
* line 7128 of /lib/accesslib.php: call to context->get_parent_context()
* line 232 of /lib/classes/event/base.php: call to context_module->get_course_context()
* line 436 of /mod/quiz/locallib.php: call to core\event\base::create()
* line 60 of /local/deleteoldquizattempts/classes/helper.php: call to quiz_delete_attempt()
* line 228 of /local/deleteoldquizattempts/classes/helper.php: call to local_deleteoldquizattempts\helper->delete_attempts()
* line 52 of /local/deleteoldquizattempts/cli/delete_attempts.php: call to local_deleteoldquizattempts\helper->delete_attempts_cli_handler()

**Comment by vadimonus** [comment]
done
